name: shared
description: A new Flutter project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  async: 2.11.0
  dartx: 1.1.0
  decimal: 2.3.2
  device_info_plus: 8.1.0
  flutter_cache_manager: 3.3.0
  injectable: 2.1.1
  intl: 0.18.0
  mime: 1.0.4
  package_info_plus: 3.0.3
  path_provider: 2.0.13
  rxdart: 0.27.7
  timezone: 0.9.1
  url_launcher: 6.1.10
  freezed_annotation: 2.2.0

dev_dependencies:
  flutter_lints: 2.0.1
  dart_code_metrics: 5.7.4
  build_runner: 2.3.3
  freezed: 2.3.2
  freezed_annotation: 2.2.0
  injectable_generator: 2.1.5
  mocktail: 0.3.0