name: initializer
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependency_overrides:
  analyzer: 5.13.0

dependencies:
  flutter:
    sdk: flutter
  data:
    path: ../data
  domain:
    path: ../domain
  resources:
    path: ../resources
  shared:
    path: ../shared

dev_dependencies:
  flutter_lints: 2.0.1
