name: resources
description: A new Flutter package project.
version: 0.0.1
publish_to: none
environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: 5.9.0
  flutter_svg: 2.0.10+1
  intl: 0.19.0
  slang: 3.30.2
  slang_flutter: 3.30.0
  shared:
    path: ../shared
dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: 2.8.7
  custom_lint: 0.6.5
  flutter_lints: 3.0.2
  build_runner: 2.4.9
  flutter_gen_runner: 5.4.0
  slang_build_runner: 3.30.0
flutter_gen:
  output: lib/src/generated
  line_length: 160
  null_safety: true
  integrations:
    flutter_svg: true
    # flare_flutter: true
  assets:
    outputs:
      package_parameter_enabled: true
  fonts:
    enabled: true
    outputs:
      package_parameter_enabled: true
  # colors:
  #   enabled: true
  #   inputs:
  #     - assets/color/colors.xml
flutter:
  uses-material-design: true
  generate: false
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: FontAwesomeSolid
      fonts:
        - asset: assets/fonts/fa_icon/fa-solid-900.ttf
    - family: FontAwesomeSharpSolid
      fonts:
        - asset: assets/fonts/fa_icon/fa-sharp-solid-900.ttf
    - family: FontAwesomeDuoTone
      fonts:
        - asset: assets/fonts/fa_icon/fa-duotone-900.ttf
    - family: FontAwesomeBrand
      fonts:
        - asset: assets/fonts/fa_icon/fa-brands-400.ttf
    - family: FontAwesomeRegular
      fonts:
        - asset: assets/fonts/fa_icon/fa-regular-400.ttf
    - family: FontAwesomeLight
      fonts:
        - asset: assets/fonts/fa_icon/fa-light-300.ttf
    - family: FontAwesomeThin
      fonts:
        - asset: assets/fonts/fa_icon/fa-thin-100.ttf
