name: resources
description: A new Flutter project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: 5.7.0
  intl: 0.18.0
  slang: 3.15.0
  slang_flutter: 3.15.0

  shared:
    path: ../shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
  dart_code_metrics: 5.7.4
  build_runner: 2.3.3
  flutter_gen_runner: 5.2.0
  slang_build_runner: 3.15.0

flutter_gen:
  output: lib/src/generated
  line_length: 160
  null_safety: true

  integrations:
    flutter_svg: true
    # flare_flutter: true

  assets:
    enabled: true

  fonts:
    enabled: true

  # colors:
  #   enabled: true
  #   inputs:
  #     - assets/color/colors.xml

flutter:
  uses-material-design: true
  generate: false
  assets:
    - assets/images/

  fonts:
    - family: FontAwesomeSolid
      fonts:
        - asset: assets/fonts/fa_icon/fa-solid-900.ttf
    - family: FontAwesomeSharpSolid
      fonts:
        - asset: assets/fonts/fa_icon/fa-sharp-solid-900.ttf
    - family: FontAwesomeDuoTone
      fonts:
        - asset: assets/fonts/fa_icon/fa-duotone-900.ttf
    - family: FontAwesomeBrand
      fonts:
        - asset: assets/fonts/fa_icon/fa-brands-400.ttf
    - family: FontAwesomeRegular
      fonts:
        - asset: assets/fonts/fa_icon/fa-regular-400.ttf
    - family: FontAwesomeLight
      fonts:
        - asset: assets/fonts/fa_icon/fa-light-300.ttf
    - family: FontAwesomeThin
      fonts:
        - asset: assets/fonts/fa_icon/fa-thin-100.ttf
