name: nals_lints
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"



dependencies:
  custom_lint_builder:
  flutter:
    sdk: flutter
  source_gen:

dev_dependencies:
  flutter_test:
    sdk: flutter
