name: domain
description: Library domain of clean architecture.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.16.1"



dependencies:
  async:
  dartx:
  get_it:
  injectable:
  meta:
  resources:
    path: ../resources
  rxdart:
  shared:
    path: ../shared

  flutter:
    sdk: flutter
dev_dependencies:
  build_runner:
  custom_lint:
  flutter_lints:
  flutter_test:
    sdk: flutter
  freezed:
  freezed_annotation:
  injectable_generator:
  logging:
  mocktail:
  nals_lints:
    path: ../nals_lints