name: domain
description: Library domain of clean architecture.
version: 0.0.1
publish_to: none
environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.16.1"
dependencies:
  async: 2.11.0
  dartx: 1.2.0
  get_it: 7.6.8
  injectable: 2.4.4
  meta: 1.15.0
  resources:
    path: ../resources
rxdart:
  shared:
    path: ../shared
  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: 2.4.9
custom_lint:
  flutter_lints: 3.0.2
  flutter_test:
    sdk: flutter
  freezed: 2.4.7
  freezed_annotation: 2.4.1
  injectable_generator: 2.6.1
  logging: 1.2.0
  mocktail: 1.0.3
  nals_lints:
    path: ../nals_lints
