name: domain
description: Library domain of clean architecture.
version: 0.0.1
publish_to: none
environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.16.1"
dependencies:
  async: 2.11.0
  dartx: 1.2.0
  get_it: 7.7.0
  injectable: 2.4.4
  meta: 1.15.0
  resources:
    path: ../resources
  rxdart: 0.28.0
  shared:
    path: ../shared
  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: 2.4.12
  custom_lint: 0.6.5
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter
  freezed: 2.5.7
  freezed_annotation: 2.4.4
  injectable_generator: 2.6.2
  logging: 1.2.0
  mocktail: 1.0.4
  nals_lints:
    path: ../nals_lints
