name: app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.5 <4.0.0"
dependencies:
  auto_route: 9.2.2
  get_it: 7.7.0
  injectable: 2.4.4
  cached_network_image: 3.4.1
  cupertino_icons: 1.0.8
  flutter_bloc: 8.1.6
  flutter_screenutil: 5.9.3
  infinite_scroll_pagination: 4.0.0
  carousel_slider: 5.0.0
  camera: 0.11.0+2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  data:
    path: ../data
  domain:
    path: ../domain
  initializer:
    path: ../initializer
  resources:
    path: ../resources
  rxdart: 0.28.0
  shared:
    path: ../shared
dev_dependencies:
  auto_route_generator: 9.0.0
  bloc_test: 9.1.7
  build_runner: 2.4.12
  custom_lint: 0.6.5
  flutter_launcher_icons: 0.13.1
  flutter_lints: 4.0.0
  flutter_native_splash: 2.4.1
  flutter_test:
    sdk: flutter
  freezed: 2.5.7
  freezed_annotation: 2.4.4
  injectable_generator: 2.6.2
  logging: 1.2.0
  mocktail: 1.0.4
  nals_lints:
    path: ../nals_lints
flutter:
  uses-material-design: true
