name: app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.5 <4.0.0"
dependencies:
  auto_route: 8.0.3
  get_it: 7.6.8
  injectable: 2.4.4
  cached_network_image: 3.3.1
  cupertino_icons: 1.0.6
  flutter_bloc: 8.1.5
  flutter_screenutil: 5.9.0
  infinite_scroll_pagination: 4.0.0
  carousel_slider: 4.2.1
  camera: 0.11.0+2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  data:
    path: ../data
  domain:
    path: ../domain
  initializer:
    path: ../initializer
  resources:
    path: ../resources
  rxdart: 0.28.0
  shared:
    path: ../shared
dev_dependencies:
  auto_route_generator: 8.0.0
  bloc_test: 9.1.7
  build_runner: 2.4.9
  custom_lint: 0.6.5
  flutter_launcher_icons: 0.13.1
  flutter_lints: 3.0.2
  flutter_native_splash: 2.4.0
  flutter_test:
    sdk: flutter
  freezed: 2.4.7
  freezed_annotation: 2.4.1
  injectable_generator: 2.6.2
  logging: 1.2.0
  mocktail: 1.0.3
  nals_lints:
    path: ../nals_lints
flutter:
  uses-material-design: true
