name: app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  async:
  auto_route:
  get_it:
  injectable:

  cached_network_image:
  cupertino_icons:
  dartx:
  flutter_bloc:
  flutter_screenutil:
  infinite_scroll_pagination:
  carousel_slider:

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  data:
    path: ../data
  domain:
    path: ../domain
  initializer:
    path: ../initializer
  resources:
    path: ../resources
  rxdart:
  shared:
    path: ../shared
dev_dependencies:
  auto_route_generator:
  bloc_test:
  build_runner:
  custom_lint:
  flutter_launcher_icons:
  flutter_lints:
  flutter_native_splash:
  flutter_test:
    sdk: flutter
  freezed:
  freezed_annotation:
  injectable_generator:
  logging:
  mocktail:
  nals_lints:
    path: ../nals_lints

flutter:
  uses-material-design: true
