name: app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.5 <4.0.0"

dependency_overrides:
  analyzer: 5.13.0

dependencies:
  async: 2.11.0
  get_it: 7.6.0
  injectable: 2.1.2

  auto_route: 7.6.0
  cached_network_image: 3.2.1
  cupertino_icons: 1.0.3
  dartx: 1.1.0
  flutter_bloc: 8.1.2
  flutter_local_notifications: 13.0.0
  flutter_screenutil: 5.8.4
  flutter_svg: 2.0.7
  infinite_scroll_pagination: 3.2.0
  carousel_slider: 4.2.1
  flutter_tts: 3.7.0

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  data:
    path: ../data
  domain:
    path: ../domain
  initializer:
    path: ../initializer
  resources:
    path: ../resources
  rxdart: 0.27.7
  shared:
    path: ../shared
dev_dependencies:
  auto_route_generator: 7.1.1
  bloc_test: 9.1.3
  build_runner: 2.4.5
  custom_lint: 0.5.0
  flutter_launcher_icons: 0.9.2
  flutter_lints: 2.0.1
  flutter_native_splash: 2.2.16
  flutter_test:
    sdk: flutter
  freezed: 2.3.5
  freezed_annotation: 2.2.0
  injectable_generator: 2.1.6
  logging: 1.1.1
  mocktail: 0.3.0
  nals_lints:
    path: ../nals_lints

flutter:
  uses-material-design: true
