name: shared
description: A new Flutter package project.
version: 0.0.1
publish_to: none
environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"
dependencies:
  android_id: 0.3.6
  async: 2.11.0
  dartx: 1.2.0
  decimal: 2.3.3
  device_info_plus: 10.0.1
  flutter:
    sdk: flutter
  flutter_cache_manager: 3.4.1
  flutter_udid: 3.0.0
  injectable: 2.4.4
  intl: 0.19.0
  mime: 1.0.5
  package_info_plus: 6.0.0
  path_provider: 2.1.4
  rxdart: 0.28.0
  timezone: 0.9.2
  url_launcher: 6.2.5
dev_dependencies:
  build_runner: 2.4.9
  custom_lint: 0.6.5
  flutter_lints: 3.0.2
  flutter_test:
    sdk: flutter
  freezed: 2.4.7
  freezed_annotation: 2.4.1
  injectable_generator: 2.6.2
  logging: 1.2.0
  mocktail: 1.0.3
  nals_lints:
    path: ../nals_lints
