name: shared
description: A new Flutter package project.
version: 0.0.1
publish_to: none
environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"
dependencies:
  android_id: 0.4.0
  async: 2.11.0
  dartx: 1.2.0
  decimal: 3.0.2
  device_info_plus: 10.1.2
  flutter:
    sdk: flutter
  flutter_cache_manager: 3.4.1
  flutter_udid: 3.0.0
  injectable: 2.4.4
  intl: 0.19.0
  mime: 1.0.6
  package_info_plus: 8.0.2
  path_provider: 2.1.4
  rxdart: 0.28.0
  timezone: 0.9.4
  url_launcher: 6.3.0
dev_dependencies:
  build_runner: 2.4.12
  custom_lint: 0.6.5
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter
  freezed: 2.5.7
  freezed_annotation: 2.4.4
  injectable_generator: 2.6.2
  logging: 1.2.0
  mocktail: 1.0.4
  nals_lints:
    path: ../nals_lints
