name: domain
description: Library domain of clean architecture.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  async: 2.10.0
  rxdart: 0.27.7
  get_it: 7.2.0
  injectable: 2.1.1
  freezed_annotation: 2.2.0


  shared:
    path: ../shared

  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: 2.3.3
  dart_code_metrics: 5.7.0
  freezed: 2.3.2
  injectable_generator: 2.1.5

  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0
  mocktail: 0.3.0
